'use strict';
const $ = id => document.getElementById(id);
const colors = {SRAM:'#168779',DRAM:'#3274b9',ReRAM:'#d55c45',MTJ:'#885bb1',FeFET:'#b47c16'};
const symbols = {SRAM:'cross',DRAM:'triangle-left',ReRAM:'triangle-up',MTJ:'square',FeFET:'diamond'};
const figures = {
 '6a':{title:'Cell area vs. process node',x:'process_node_nm',y:'area_um2',xlabel:'Process node (nm)',ylabel:'Cell area (µm²)',file:'fig06a_area_vs_process_node.png',scale:'log'},
 '6b':{title:'Cell area over time',x:'year',y:'area_um2',xlabel:'Publication year',ylabel:'Cell area (µm²)',file:'fig06b_area_vs_year.png',scale:'paper'},
 '7a':{title:'Information density vs. process node',x:'process_node_nm',y:'information_density_bits_per_um2',xlabel:'Process node (nm)',ylabel:'Information density (bits/µm²)',file:'fig07a_information_density_vs_process_node.png',scale:'log'},
 '7b':{title:'Layout-normalized search energy',x:'year',y:'layout_normalized_search_energy',xlabel:'Publication year',ylabel:'Layout-normalized energy (fJ/bit/search)',file:'fig07b_layout_normalized_search_energy_vs_year.png',scale:'log'}
};
const state = {figure:'6a',tech:new Set(Object.keys(colors)),mode:'all',node:'all',from:0,to:9999,labels:false,scale:'log',selected:null};
let data=[],visible=[],plotReady=false,renderNumber=0;
const esc = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = n => n===null||n===undefined?'Not reported':new Intl.NumberFormat('en-US',{maximumSignificantDigits:4,useGrouping:false}).format(n);
function tell(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(tell.timer);tell.timer=setTimeout(()=>$('toast').hidden=true,3000);}
function included(rows=data){const f=figures[state.figure];return rows.filter(d=>state.tech.has(d.technology)&&(state.mode==='all'||d.storage_mode_for_plot===state.mode)&&d.storage_mode_for_plot&&(state.node==='all'||d.process_node_nm===Number(state.node))&&d.year>=state.from&&d.year<=state.to&&d[f.x]!==null&&d[f.y]!==null&&(state.scale!=='log'||d[f.y]>0));}
function reset(){state.tech=new Set(Object.keys(colors));state.mode='all';state.node='all';state.from=Math.min(...data.map(d=>d.year));state.to=Math.max(...data.map(d=>d.year));state.labels=false;state.scale=figures[state.figure].scale;state.selected=null;syncControls();render();}
function syncControls(){document.querySelectorAll('[data-tech]').forEach(el=>el.checked=state.tech.has(el.dataset.tech));document.querySelectorAll('[data-mode]').forEach(el=>{el.classList.toggle('active',el.dataset.mode===state.mode);el.setAttribute('aria-pressed',el.dataset.mode===state.mode);});$('year-from').value=state.from;$('year-to').value=state.to;$('node').value=state.node;$('labels').checked=state.labels;$('scale').querySelector('[value="paper"]').disabled=state.figure!=='6b';$('scale').value=state.scale;}
function chooseFigure(key){state.figure=key;state.scale=figures[key].scale;document.querySelectorAll('[data-figure]').forEach(el=>{const active=el.dataset.figure===key;el.classList.toggle('active',active);el.setAttribute('aria-selected',active);el.tabIndex=active?0:-1;});$('plot-view').setAttribute('aria-labelledby','tab-'+key);syncControls();render();}
function selectDesign(id){state.selected=id;render();}
function detail(){const d=data.find(row=>row.source_row===state.selected);if(!d){$('design-detail').innerHTML='<div class="spotlight-empty"><span class="target-icon">⊙</span><h3>Every point has a story.</h3><p>Select a point in the chart or a row below to explore its circuit, metrics, and source paper.</p></div><div class="mini-guide"><span>01</span><p>Choose a figure</p><span>02</span><p>Narrow the technologies</p><span>03</span><p>Inspect a design</p></div>';return;}
const metric=(label,value,unit)=>`<div><span>${label}</span><strong>${fmt(value)} <small>${unit}</small></strong></div>`;
$('design-detail').innerHTML=`<div class="design-ref"><span class="design-tag" style="--color:${colors[d.technology]}">${esc(d.technology)} · Ref. ${d.manuscript_reference_number}</span><button id="clear-selection" aria-label="Clear selected design">Clear ×</button></div><h3 class="design-title">${esc(d.cell_structure)}<br>${esc(d.cam_concept)} cell</h3><p class="paper-title">${esc(d.paper_title)}</p><div class="metrics">${metric('Cell area',d.area_um2,'µm²')}${metric('Process node',d.process_node_nm,'nm')}${metric('Density',d.information_density_bits_per_um2,'bits/µm²')}${metric('Year',d.year,'')}</div><div class="detail-extra"><p>Storage: <b>${esc(d.storage_mode_for_plot||'Not reported')}</b> · ${fmt(d.states_stored)} states</p><p>Reported energy: <b>${fmt(d.search_energy_fj_per_bit_per_search)}</b>${d.search_energy_fj_per_bit_per_search===null?'':' fJ/bit/search'}</p><p>Layout factor k: <b>${fmt(d.layout_factor_k)}</b></p><p>Normalized energy: <b>${fmt(d.layout_normalized_search_energy)}</b>${d.layout_normalized_search_energy===null?'':' fJ/bit/search'}</p><p>Final-proof reference: <b>[${d.proof_reference_number}]</b></p></div><a class="source-button" href="${d.doi?'https://doi.org/'+encodeURI(d.doi):'https://scholar.google.com/scholar?q='+encodeURIComponent(d.paper_title)}" target="_blank" rel="noreferrer">${d.doi?'Open source paper':'Find source paper'} ↗</a>${visible.some(v=>v.source_row===d.source_row)?'':'<p class="selection-note">This design is not plotted in the current view. A required value may be missing, or a filter may exclude it.</p>'}`;
$('clear-selection').onclick=()=>{state.selected=null;render();};}
function renderTable(){const fields=['year','process_node_nm','area_um2','information_density_bits_per_um2','search_energy_fj_per_bit_per_search'];$('design-table').innerHTML=visible.map(d=>`<tr data-id="${d.source_row}" class="${d.source_row===state.selected?'selected':''}" aria-selected="${d.source_row===state.selected}"><td><button aria-label="Inspect reference ${d.manuscript_reference_number}: ${esc(d.paper_title)}">[${d.manuscript_reference_number}]<span class="cell-name">${esc(d.cell_structure)}</span></button></td><td><span class="tech-pill" style="--color:${colors[d.technology]}">${esc(d.technology)}</span></td><td>${esc(d.storage_mode_for_plot)}</td>${fields.map(k=>`<td>${d[k]===null?'<span title="Not reported">—</span>':fmt(d[k])}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="8">No designs match the current filters.</td></tr>';$('table-count').textContent=visible.length;document.querySelectorAll('#design-table tr[data-id]').forEach(el=>{el.onclick=()=>selectDesign(Number(el.dataset.id));});}
async function render(){const revision=++renderNumber;visible=included();const f=figures[state.figure];$('chart-title').textContent=f.title;$('figure-kicker').textContent='FIGURE '+state.figure;$('point-count').textContent=visible.length+' of 41 designs';$('published-link').href='p02_figures/'+f.file;$('legend').innerHTML=Object.entries(colors).filter(([t])=>state.tech.has(t)).map(([t,c])=>`<span><i class="dot" style="--color:${c}"></i>${t}</span>`).join('');$('empty').hidden=visible.length>0;$('plot').hidden=visible.length===0;$('export-data').disabled=!visible.length;$('export-plot').disabled=!visible.length;renderTable();detail();if(!visible.length)return;
const traces=[];const broken=state.figure==='6b'&&state.scale==='paper';
for(const [tech,color] of Object.entries(colors)){for(const mode of ['Digital','Analog']){const rows=visible.filter(d=>d.technology===tech&&d.storage_mode_for_plot===mode);if(!rows.length)continue;const trace={type:'scatter',mode:state.labels?'markers+text':'markers',name:tech+' · '+mode,x:rows.map(d=>d[f.x]),y:rows.map(d=>d[f.y]),customdata:rows.map(d=>d.source_row),text:rows.map(d=>'['+d.manuscript_reference_number+']'),textposition:'top right',textfont:{size:11,color:'#486076'},marker:{color, size:rows.map(d=>d.source_row===state.selected?17:11),symbol:mode==='Digital'?symbols[tech]+'-open':symbols[tech],line:{width:1.8,color},opacity:rows.map(d=>state.selected&&d.source_row!==state.selected?.45:1)},hovertext:rows.map(d=>`<b>[${d.manuscript_reference_number}] ${esc(d.cell_structure)} · ${tech}</b><br>${mode} · ${d.year}<br>${f.xlabel}: ${fmt(d[f.x])}<br>${f.ylabel}: ${fmt(d[f.y])}<br><i>Click to inspect source and metrics</i>`),hovertemplate:'%{hovertext}<extra></extra>',cliponaxis:true,showlegend:false};traces.push(trace);if(broken)traces.push({...trace,yaxis:'y2'});}}
const axis={showline:true,linecolor:'#b9c4cf',linewidth:1,mirror:true,zeroline:false,gridcolor:'#e4e9ee',gridwidth:1,tickfont:{size:11,color:'#6b7b8c'},ticks:'outside',ticklen:4,tickcolor:'#b9c4cf',automargin:true};
const mobile=window.innerWidth<760;
const layout={paper_bgcolor:'#fff',plot_bgcolor:'#fcfdfe',font:{family:'Arial, sans-serif',color:'#29425e'},margin:{l:mobile?64:77,r:mobile?23:28,t:18,b:56},hoverlabel:{bgcolor:'#fff',bordercolor:'#ccd7e1',font:{size:12,color:'#183250'}},xaxis:{...axis,title:{text:f.xlabel,font:{size:12,color:'#506378'},standoff:15},...(f.x==='process_node_nm'?{range:[260,5],tickvals:[16,28,45,65,90,130,180,250],ticktext:mobile?['','28','','65','','130','180','250']:undefined}:{dtick:5,range:[1999.5,2024.5],tickformat:'d'})},yaxis:{...axis,type:state.scale==='log'?'log':'linear',title:{text:f.ylabel,font:{size:12,color:'#506378'},standoff:12},...(state.scale==='log'?{dtick:1,exponentformat:'power'}:{rangemode:'tozero'})},dragmode:'zoom',showlegend:false,uirevision:state.figure+'-'+state.scale+'-'+Array.from(state.tech).join()+'-'+state.mode+'-'+state.node+'-'+state.from+'-'+state.to};
if(broken){layout.yaxis={...layout.yaxis,range:[-2,25],domain:[0,.64],tickvals:[0,10,20]};layout.yaxis2={...axis,range:[35,56],domain:[.72,1],tickvals:[40,50],anchor:'x'};layout.xaxis.anchor='y';layout.shapes=[0,1].flatMap(x=>[.66,.70].map(y=>({type:'line',xref:'paper',yref:'paper',x0:x-.009,x1:x+.009,y0:y-.01,y1:y+.01,line:{color:'#6b7b8c',width:1.3}})));}
$('chart-note').textContent=broken?'Published broken axis: 25–35 µm² omitted. Drag to zoom; click a point to inspect.':'Drag to zoom · Click a point to inspect · Double-click to reset zoom';
try{await Plotly.react('plot',traces,layout,{responsive:true,displayModeBar:false,scrollZoom:false,displaylogo:false});if(revision!==renderNumber)return;if(!plotReady){$('plot').on('plotly_click',event=>{const id=event.points[0]?.customdata;if(id!==undefined)selectDesign(id);});plotReady=true;}}catch(error){console.error(error);tell('The chart could not render. The data table is still available.');}}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function wire(){document.querySelectorAll('[data-tech]').forEach(el=>el.onchange=()=>{if(el.checked)state.tech.add(el.dataset.tech);else state.tech.delete(el.dataset.tech);render();});document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>{state.mode=el.dataset.mode;syncControls();render();});document.querySelectorAll('[data-figure]').forEach(el=>{el.onclick=()=>chooseFigure(el.dataset.figure);el.onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const keys=Object.keys(figures);let i=keys.indexOf(state.figure);i=event.key==='Home'?0:event.key==='End'?3:(i+(event.key==='ArrowRight'?1:3))%4;chooseFigure(keys[i]);$('tab-'+keys[i]).focus();}};});$('year-from').onchange=()=>{state.from=Number($('year-from').value);if(state.from>state.to)state.to=state.from;syncControls();render();};$('year-to').onchange=()=>{state.to=Number($('year-to').value);if(state.to<state.from)state.from=state.to;syncControls();render();};$('node').onchange=()=>{state.node=$('node').value;render();};$('labels').onchange=()=>{state.labels=$('labels').checked;render();};$('scale').onchange=()=>{state.scale=$('scale').value;render();};$('reset').onclick=reset;$('empty-reset').onclick=reset;$('reset-zoom').onclick=()=>{if(!visible.length)return;const f=figures[state.figure];const update={'xaxis.range':f.x==='process_node_nm'?[260,5]:[1999.5,2024.5],'yaxis.autorange':true};if(state.figure==='6b'&&state.scale==='paper'){update['yaxis.autorange']=false;update['yaxis.range']=[-2,25];update['yaxis2.range']=[35,56];}Plotly.relayout('plot',update);};$('export-plot').onclick=async()=>{try{await Plotly.downloadImage('plot',{format:'svg',filename:'cam-figure-'+state.figure,width:1000,height:620});tell('Chart exported as SVG.');}catch(error){tell('Export failed. Please try again.');}};$('export-data').onclick=()=>{const keys=Object.keys(data[0]);const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';download([keys.join(','),...visible.map(d=>keys.map(k=>cell(d[k])).join(','))].join('\r\n'),'cam-figure-'+state.figure+'-filtered.csv','text/csv;charset=utf-8');tell(visible.length+' designs exported.');};}
async function init(){try{const response=await fetch('p00_data/designs.json');if(!response.ok)throw Error('Dataset unavailable');data=await response.json();$('technologies').innerHTML=Object.entries(colors).map(([tech,color])=>`<label class="tech-label"><input type="checkbox" data-tech="${tech}" checked><i class="dot" style="--color:${color}"></i><span>${tech}</span><span class="tech-count">${data.filter(d=>d.technology===tech).length}</span></label>`).join('');const years=[...new Set(data.map(d=>d.year))].sort((a,b)=>a-b);for(const id of ['year-from','year-to'])$(id).innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');$('node').innerHTML+=[...new Set(data.map(d=>d.process_node_nm).filter(v=>v!==null))].sort((a,b)=>a-b).map(n=>`<option value="${n}">${n} nm</option>`).join('');wire();reset();document.querySelectorAll('[data-figure]').forEach(el=>el.tabIndex=el.dataset.figure===state.figure?0:-1);}catch(error){console.error(error);$('point-count').textContent='Data unavailable';$('empty').hidden=false;$('empty').innerHTML='<strong>The dataset could not load.</strong><p>Please reload the page, or open the source dataset.</p><a href="https://github.com/tmo324/cam-circuits-survey-data">Open dataset ↗</a>';}}
init();
